<?php
//
// File generated by Berp3 installer 15.0.0-alpha on Nov 09, 2021
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$berp3_main_url_root='https://localhost/berp3';
$berp3_main_document_root='C:/xampp/htdocs/berp3';
$berp3_main_url_root_alt='/custom';
$berp3_main_document_root_alt='C:/xampp/htdocs/berp3/custom';
$berp3_main_data_root='C:/xampp/htdocs/berp3/documents';
$berp3_main_db_host='localhost';
$berp3_main_db_port='3306';
$berp3_main_db_name='berp3';
$berp3_main_db_prefix='erp_';
$berp3_main_db_user='root';
$berp3_main_db_pass='';
$berp3_main_db_type='mysqli';
$berp3_main_db_character_set='utf8';
$berp3_main_db_collation='utf8_unicode_ci';
// Authentication settings
$berp3_main_authentication='berp3';

//$berp3_main_demo='autologin,autopass';
// Security settings
$berp3_main_prod='0';
$berp3_main_force_https='1';
$berp3_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
$berp3_nocsrfcheck='0';
$berp3_main_instance_unique_id='e00c4204576270a0fb4cba99ee7648fa';
$berp3_mailing_limit_sendbyweb='0';

//$berp3_lib_FPDF_PATH='';
//$berp3_lib_TCPDF_PATH='';
//$berp3_lib_FPDI_PATH='';
//$berp3_lib_TCPDI_PATH='';
//$berp3_lib_ADODB_PATH='';
//$berp3_lib_GEOIP_PATH='';
//$berp3_lib_NUSOAP_PATH='';
//$berp3_lib_ODTPHP_PATH='';
//$berp3_lib_ODTPHP_PATHTOPCLZIP='';
//$berp3_js_CKEDITOR='';
//$berp3_js_JQUERY='';
//$berp3_js_JQUERY_UI='';

//$berp3_font_DOL_DEFAULT_TTF='';
//$berp3_font_DOL_DEFAULT_TTF_BOLD='';
$berp3_main_distrib='standard';
